my_string = input('Напишите что-нибудь приличное:  ')
print(len(my_string))
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(' ', ''))
print(list(my_string[0]))
print(list(my_string[-1]))